approve_by_comment: true
approve_regex: (^Approved|^RTM)
reject_regex: (^Rejected|^Fix it)
reset_on_push: false
reviewers:
  -
    name: backend-devs
    required: 1
    members:
      - duramato
      - fernandog
      - labrys
      - medariox
      - p0psicles
      - adaur
# # CONDITIONS REQUIRE PRO ACCOUNT
#    conditions:
#      branches:
#        - master
#        - beta
#        - develop
#      files:
#        - "*.py"
  -
    name: gui-devs
    required: 1
    members:
      - labrys
      - OmgImAlexis
      - p0psicles
# # CONDITIONS REQUIRE PRO ACCOUNT
#    conditions:
#      branches:
#        - master
#        - beta
#        - develop
#      files:
#        - "gui/"
  -
    name: support
    required: 0
    members:
      - neoatomic
