language:
  - python

python: 2.7.9

sudo: false

branches:
  except:
    - master

before_install:
  - npm install -g grunt-cli
  - npm install -g bower
  - cd .build && npm install && bower install && cd ..

script:
  - ./tests/all_tests.py
  - cd .build && grunt travis && cd ..

cache:
  directories:
    - $HOME/.cache/pip
    - .build/bower_components
    - .build/node_modules

after_failure:
  - cat ./Logs/sickrage.log

notifications:
  irc: "irc.freenode.net#sickrage-builds"

  email:
    on_success: change
    on_failure: change
